### ISSUE TITLE
Firebase?

### ISSUE THREAD

**Issue by mikedizon** [abachuk/fullbag-react-redux-dashboard#1]
Is firebase required to run this?

**Comment by abachuk** [comment]
that's the starting point. Ideally it should work with any remote server. just call any API.

**Comment by mikedizon** [comment]
Is there a way to bypass login and poke around?

On Sunday, April 3, 2016, Alex Bachuk notifications@github.com wrote:

> that's the starting point. Ideally it should work with any remote server.
> just call any API.
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> https://github.com/abachuk/fullbag-react-redux-dashboard/issues/1#issuecomment-204995067

## 

Sent from Gmail Mobile
